# Generated by Django 4.1.6 on 2023-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bank_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='history',
            field=models.ManyToManyField(blank=True, to='core.profile'),
        ),
    ]
