# Generated by Django 4.1.6 on 2023-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bank_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('REUSE', 'REUSE'), ('USED', 'USED'), ('FAILED', 'FAILED')], default='LIVE', max_length=20),
        ),
    ]
