# Generated by Django 4.1.6 on 2023-03-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_earning_profile_pending_alter_bank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('PENDING SUBMIT', 'PENDING SUBMIT')], default='LIVE', max_length=20),
        ),
    ]
