# Generated by Django 4.1.6 on 2023-03-30 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
